---
title: Matching
subtitle: {path}
date: {date}
output:
  html_document:
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 2
    theme: lumen
---

<style>
/* Make content use more width even with floating TOC */
.main-container {
  max-width: 100% !important;
}

/* Give it some margin so it's not glued to window edge */
.main-container {
  margin-left: 1em;
  margin-right: 1em;
}
</style>


# Target comparison

```{r create comparison plots, include=F}
comparisonPlots <- reportbrick::showMatchingComparison("{path}", showTitles = FALSE)
```


```{r comparison plot loop, results='asis',fig.width=15, fig.height={figHeight}, echo=F, message=F, warning=F}
for (ref in names(comparisonPlots)) {
  plotRef <- comparisonPlots[[ref]]
  if (is.null(plotRef)) {
    next
  }
  cat(paste("##", ref))
  if (inherits(plotRef, "ggplot")) {
    cat("\n\n")
    print(plotRef)
  } else {
    cat("{.tabset .tabset-pills}\n\n")
    for (tab in names(plotRef)) {
      plotTab <- plotRef[[tab]]
      cat(paste0("### ", tab, "\n\n"))
      print(plotTab)
      cat("\n\n")
    }
  }
  cat("\n\n")
}
```


# Removal of standing heating systems

```{r create standing stock plots, include=F}
standingPlots <- reportbrick::showMatchingStandingStock("{path}")
```

```{r standing stock plot loop, results='asis',fig.width=15, fig.height=8, echo=F, message=F, warning=F}
for (reg in names(standingPlots)) {
  plotReg <- standingPlots[[reg]]
  cat(paste("## ", reg, "{.tabset .tabset-pills}\n\n"))
  for (tab in names(plotReg)) {
    plotTab <- plotReg[[tab]]
    cat(paste0("### ", tab, "\n\n"))
    print(plotTab)
    cat("\n\n")
  }
  cat("\n\n")
}
```
