# CO2 emissions

## All buildings

## Residential

### Space heating

```{r Emi-CO2-Residential-Space heating-(carrierHeating)}
tot <- "Emi|CO2|Residential|Space heating"
vars <- paste(tot, carrierHeating, sep = "|")
showAreaAndBarPlots(data, vars = vars, tot = tot, orderVars = "user", scales = "fixed")
walk(vars, showLinePlots, data = data)

```

#### by building type
```{r Emi-CO2-Residential-(type)-Space heating-(carrierHeating)}
for (typ in type) {
  tot <- paste0("Emi|CO2|Residential|", typ, "|Space heating")
  vars <- paste(tot, carrierHeating, sep = "|")
  showAreaAndBarPlots(data, vars = vars, tot = tot, orderVars = "user", scales = "fixed")
  walk(vars, showLinePlots, data = data)
}
```

#### by location
```{r Emi-CO2-Residential-(location)-Space heating-(carrierHeating)}
for (loc in location) {
  tot <- paste0("Emi|CO2|Residential|", loc, "|Space heating")
  vars <- paste(tot, carrierHeating, sep = "|")
  showAreaAndBarPlots(data, vars = vars, tot = tot, orderVars = "user", scales = "fixed")
  walk(vars, showLinePlots, data = data)
}
```



## Commercial
